apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nitpick
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: nitpick:latest
